  apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      app: "nginx"


    name: "nginx-service"
  spec:
    ports:
    - port: 80
      nodePort: 30000
    selector:
      app: "nginx"


    type: "NodePort"
